src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 * @ORM\Table
 */
class Task
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue()
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Vous devez saisir un titre.")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Vous devez saisir du contenu.")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDone;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true, unique=false)
     */
    private $user_id;

    public function __construct()
    {
        $this->createdAt = new \Datetime();
        $this->isDone = false;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content)
    {
        $this->content = $content;
    }

    public function isDone()
    {
        return $this->isDone;
    }

    public function toggle($flag)
    {
        $this->isDone = $flag;
    }

    public function getIsDone(): ?bool
    {
        return $this->isDone;
    }

    public function setIsDone(bool $isDone): self
    {
        $this->isDone = $isDone;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content', TextareaType::class)
        ;
    }
}

templates/task/create.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block body %}

    <div>
        {{ form_start(form, {'action' : path('task_create')}) }}
            {{ form_widget(form) }}

        <button type="submit" class="btn btn-success pull-right">save</button>
        <a href="{{ path('task_list') }}" class="btn btn-primary">Retour à la liste des tâches</a>
        {{ form_end(form) }}

    </div>
{% endblock %}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        {{ form_start(form, {'action' : path('task_edit', { 'id' : task.id })}) }}
            {{ form_widget(form) }}

            <button type="submit" class="btn btn-success pull-right">Modifier</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/task/list.html.twig
{% extends 'base.html.twig' %}

{% block header_img %}<img class="slide-image" src="{{ asset('img/todolist_content.jpg') }}" alt="todo list">{% endblock %}

{% block body %}
    <a href="{{ path('task_create') }}" class="btn btn-info pull-right">Créer une tâche</a>
    <h1 id="home" class="mx-auto">Mes tâches :</h1>
    <div class="row">

        {% for task in tasks %}
                  <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <div class="caption">
                    <h4 class="pull-right">
                        {% if task.isDone %}<span class="glyphicon glyphicon-ok"></span>{% else %}<span class="glyphicon glyphicon-remove"></span>{% endif %}
                    </h4>
                    <h4><a href="{{ path('task_edit', {'id' : task.id }) }}">{{ task.title }}</a></h4>
                    <p>{{ task.content }}</p>
                </div>
                <div>
                    <form action="{{ path('task_toggle', {'id' : task.id }) }}">
                        <button class="btn btn-success btn-sm pull-right">
                            {% if not task.isDone %}Marquer comme faite{% else %}Marquer non terminée{% endif %}
                        </button>
                    </form>

                    <form action="{{ path('task_delete', {'id' : task.id }) }}">
                        <button class="btn btn-danger btn-sm pull-right">Supprimer</button>
                    </form>
                    {% if task.userId == null %}
                        <p><strong>By :</strong> Anonyme </p>
                    {% else %}
                    <p><strong>By :</strong> {{ task.userId.username }}</p>
                        {% endif %}
                </div>
            </div>
        </div>

        {% else %}
            <div class="alert alert-warning" role="alert">
                Il n'y a pas encore de tâche enregistrée. <a href="{{ path('task_create') }}" class="btn btn-warning pull-right">Créer une tâche</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}